name: art_ilo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  supabase: ^2.10.2
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/artists/
    - assets/images/artstyle/
    - assets/images/artworks/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: rokh
      fonts:
        - asset: assets/fonts/Normal.ttf
          weight: 400
        - asset: assets/fonts/Medium.ttf
          weight: 500
        - asset: assets/fonts/SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Bold.ttf
          weight: 700
        - asset: assets/fonts/ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Black.ttf
          weight: 900

